version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.18.1
    filters:
      branches:
        only: master
    steps:
      - checkout
      - restore_cache:
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install Dependence
          command: pnpm install
      - run:
          name: Build
          command: pnpm build
      - save_cache:
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.cache/pnpm
      - run:
          name: Lint
          command: pnpm lint
      - deploy:
          name: Deploy via ssh
          command: |
            mkdir -p ~/.ssh
            touch ~/.ssh/known_hosts
            { ssh-keyscan $SSH_IP 2> /dev/null; } >> ~/.ssh/known_hosts
            if [ ${CIRCLE_BRANCH} = "master" ];then
                scp -r dist/* $SSH_USER@$SSH_IP:$DEPLOY_PATH
            else
                echo "Not master branch"
            fi
